import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Layout } from "../components/Layout";
import { usePostsQuery } from "../generated";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { data, error, loading } = usePostsQuery();
  if (loading) return <main className={styles.main}>Loading...</main>;

  if (error) return <main className={styles.main}>{error.message}</main>;

  // If we're here, we have some data in our data variable
  const posts = data?.posts?.nodes;
  return (
    <Layout>
      <Head>
        <title>Fran's TS - Headless WP Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>Fran's Headless WP in TS Demo</h1>
        {posts &&
          posts.map((post) => (
            <article key={post.id}>
              <h2>
                <Link href={`/[slug]`} as={`/${post.slug}`}>
                  <a>{post.title}</a>
                </Link>
              </h2>
            </article>
          ))}
      </header>
    </Layout>
  );
};

export default Home;
